<!-- This script contains code to build a web page with a form. It includes a PHP code to dynamically generate the html to display one checkbox for each of the events currently held in the EGN_events database table within the form. The user can select one or more events that they are interested in booking by clicking the checkboxes. Use the browser to look at the structure of the html generated by the php code.

You MUST NOT in any way change the php code provided OR the code within the FORM tags.

You MAY add Javascript for task 4.
You MAY modify the page to add your own navigation menu and link to your own stylesheet using additional html or php. However, please note that styling will not be marked for this assignment. -->

<?php
require_once("functions.php");
session_start();
echo makePageStart("Book an Event", "styles.css", "gridContainer");
echo makeHeader("Events Guide North");
echo makeNavMenu("Categories", array("index.php" => "Home", "bookEventsForm.php" => "Book Event", "credits.php" => "Credits"));
?>

<form id="bookingForm" action="javascript:alert('form submitted');" method="get">
	<section id="bookEvents">
		<h2>Select events</h2>
<?php
try {
	// include the file with the function for the database connection
	require_once('functions.php');
	// get database connection
	$dbConn = getConnection();
	$sqlEvents = 'SELECT eventID, eventTitle, eventStartDate, eventEndDate, catDesc, venueName, eventPrice FROM EGN_events e INNER JOIN EGN_categories c ON e.catID = c.catID INNER JOIN EGN_venues v ON e.venueID = v.venueID ORDER BY eventTitle';

	// execute the query
	$rsEvents = $dbConn->query($sqlEvents);

	while ($event = $rsEvents->fetchObject()) { //display all the results of the query so user can select them.
		$eventTitle = $event->eventTitle;
		echo "\t<div class='item'>
				<span class='eventTitle'>".filter_var($eventTitle, FILTER_SANITIZE_SPECIAL_CHARS)."</span>
				<span class='eventStartDate'>{$event->eventStartDate}</span>
            	<span class='eventEndDate'>{$event->eventEndDate}</span>
	            <span class='catDesc'>{$event->catDesc}</span>
	         	<span class='venueName'>{$event->venueName}</span>
	            <span class='eventPrice'>{$event->eventPrice}</span>
	            <span class='chosen'><input type='checkbox' name='event[]' value='{$event->eventID}' data-price='{$event->eventPrice}'></span>
	      		</div>\n";
	}
}
catch (Exception $e) {
	echo "Problem " . $e->getMessage();
}//used to catch any exceptions
?>
	</section>
	<section id="collection"> 
			<h2>Collection method</h2>
			<p>Please select whether you want your chosen event ticket(s) to be delivered to your home address (a charge applies for this) or whether you want to collect them yourself.</p>
			<p>
			Home address - &pound;7.99 <input type="radio" name="deliveryType" value="home" data-price="7.99" checked>&nbsp; | &nbsp;
			Collect from ticket office - no charge <input type="radio" name="deliveryType" value="ticketOffice" data-price="0">
			</p>
	</section>
	<section id="checkCost">
		<h2>Total cost</h2>
		Total <input type="text" name="total" size="10" readonly> <!-- Used to change the value of the total when user selects events -->
	</section>
	<section id="placeBooking">
		<h2>Place booking</h2>
		<h3>Your details</h3>
		<div id="custDetails" class="custDetails">
			Forename <input type="text" name="forename">
			Surname <input type="text" name="surname">
		</div>
		<p style="color: #FF0000; font-weight: bold;" id='termsText'>I have read and agree to the terms and conditions
		<input type="checkbox" name="termsChkbx"></p>
		<p><input type="submit" name="submit" value="Book now!" disabled></p>
	</section>
</form>
<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for task 4 of the assignment -->
<!-- Your HTML code here -->

<!-- Here you need to add Javascript or a link to a script (.js file) to process the form as required for task 4 of the assignment -->
<script src="formProcess.js"></script> <!--Script included to update webpage.-->

<?php
echo makeFooter("Events Guide North");
echo makePageEnd();
?>
